export const WORDS_4: string[] = [
  'ABLE','ARCH','ARMY','BACK','BAKE','BALL','BAND','BANK','BARE','BARK',
  'BASE','BATH','BEAR','BEAT','BELL','BELT','BEND','BEST','BIRD','BITE',
  'BLOW','BLUE','BOAT','BOLD','BOLT','BOMB','BOND','BONE','BOOK','BOOT',
  'BORN','BOWL','BULK','BURN','BUSH','BUSY','CAGE','CAKE','CALM','CAME',
  'CAMP','CARD','CARE','CART','CASE','CASH','CAST','CAVE','CHAT','CHIP',
  'CITY','CLAP','CLAY','CLIP','CLUB','CLUE','COAT','CODE','COIN','COLD',
  'COME','COOK','COOL','COPE','COPY','CORE','CORN','COST','CREW','CROP',
  'CURE','CURL','CUTE','DARK','DARE','DAWN','DEAL','DEAR','DECK','DEEP',
  'DEER','DENY','DESK','DIAL','DIET','DIRT','DISH','DOCK','DOES','DOME',
  'DONE','DOOR','DOSE','DOWN','DRAG','DRAW','DREW','DROP','DRUM','DULL',
  'DUMP','DUST','DUTY','EACH','EARN','EASE','EAST','EDGE','ELSE','EMIT',
  'ENVY','EPIC','EVEN','EVER','EVIL','EXAM','FACE','FACT','FADE','FAIL',
  'FAIR','FAKE','FALL','FAME','FANG','FARM','FAST','FATE','FEAR','FEAT',
  'FEED','FEEL','FELL','FELT','FILE','FILL','FILM','FIND','FINE','FIRE',
  'FIRM','FISH','FIST','FLAG','FLAT','FLED','FLEW','FLIP','FLOW','FOAM',
];

export const WORDS_5: string[] = [
  'ABOUT','ABOVE','ABUSE','ACTOR','ADAPT','ADMIT','ADOPT','ADULT','AFTER',
  'AGAIN','AGENT','AGREE','AHEAD','ALARM','ALBUM','ALIEN','ALIGN','ALIVE',
  'ALLOW','ALONE','ALONG','ALTER','AMPLE','ANGEL','ANGER','ANGLE','APART',
  'APPLE','APPLY','ARENA','ARISE','ASIDE','ASSET','AVOID','AWARD','AWARE',
  'BASIC','BEACH','BEGIN','BEING','BELOW','BENCH','BLACK','BLADE','BLAME',
  'BLAND','BLANK','BLAST','BLAZE','BLEED','BLEND','BLESS','BLIND','BLOCK',
  'BLOOD','BLOOM','BLOWN','BOARD','BONUS','BOOST','BOUND','BRAIN','BRAND',
  'BRAVE','BREAD','BREAK','BREED','BRICK','BRIDE','BRIEF','BRING','BROAD',
  'BROWN','BRUSH','BUILD','BURST','BUYER','CABIN','CANDY','CARRY','CATCH',
  'CAUSE','CHAIN','CHAIR','CHALK','CHAOS','CHARM','CHART','CHASE','CHEAP',
  'CHECK','CHEST','CHIEF','CHILD','CHILI','CHINA','CHOSE','CHUNK','CIVIC',
  'CLAIM','CLASH','CLASS','CLEAN','CLEAR','CLICK','CLIFF','CLIMB','CLING',
  'CLOCK','CLONE','CLOSE','CLOTH','CLOUD','COACH','COAST','COLOR','COMET',
  'COMIC','CORAL','COUNT','COURT','COVER','CRACK','CRAFT','CRANE','CRASH',
  'CRAZY','CREAM','CRIME','CROWN','CRUSH','CURVE','CYCLE','DAILY','DANCE',
  'DEATH','DEBUT','DELAY','DELTA','DENSE','DEPTH','DERBY','DEVIL','DIGIT',
  'DIRTY','DITCH','DOUBT','DRAFT','DRAIN','DRAMA','DRANK','DRAWN','DREAM',
  'DRESS','DRIED','DRIFT','DRILL','DRINK','DRIVE','DROVE','DROWN','DYING',
  'EAGER','EARLY','EARTH','EIGHT','ELECT','ELITE','EMPTY','ENEMY','ENJOY',
  'ENTER','ENTRY','EQUAL','ERROR','EVENT','EVERY','EXACT','EXERT','EXIST',
  'EXTRA','FABLE','FAITH','FALSE','FANCY','FAULT','FEAST','FENCE','FETCH',
  'FIBER','FIELD','FIFTH','FIFTY','FIGHT','FINAL','FLAME','FLASH','FLEET',
  'FLESH','FLOAT','FLOOD','FLOOR','FLOUR','FLUID','FLUSH','FLUTE','FOCAL',
  'FOCUS','FORCE','FORGE','FRAME','FRANK','FRAUD','FRESH','FRONT','FROST',
  'FROZE','FRUIT','FULLY','FUNGI','GIANT','GIVEN','GLAND','GLASS','GLOBE',
  'GLOOM','GLORY','GLOVE','GOING','GRACE','GRADE','GRAIN','GRAND','GRANT',
  'GRAPH','GRASP','GRASS','GRAVE','GREAT','GREEN','GRIND','GROSS','GROUP',
  'GROVE','GROWN','GUARD','GUESS','GUIDE','GUILT','HAPPY','HARSH','HAVEN',
  'HEART','HEAVY','HENCE','HOBBY','HONOR','HORSE','HOTEL','HOUSE','HUMAN',
];

export const WORDS_6: string[] = [
  'ABSORB','ACCEPT','ACCESS','ACROSS','ACTION','ACTIVE','ACTUAL','ADJUST',
  'ADMIRE','ADVENT','ADVICE','ADVISE','AFFORD','AGENDA','ALBEIT','ANIMAL',
  'ANNUAL','ANSWER','ANYONE','ANYWAY','APPEAL','APPEAR','ARCTIC','AROUND',
  'ARRIVE','ARTIST','ASPECT','ASSERT','ASSESS','ASSIGN','ASSIST','ASSUME',
  'ATTACH','ATTACK','ATTAIN','ATTEND','AUGUST','AUTUMN','AVENUE','BACKED',
  'BACKER','BACKUP','BANANA','BANNER','BARELY','BASKET','BATTLE','BEAUTY',
  'BECOME','BEFORE','BEHALF','BEHAVE','BEHIND','BELONG','BESIDE','BETRAY',
  'BETTER','BEYOND','BISHOP','BITTER','BLANCH','BORDER','BOTTOM','BOUNCE',
  'BRANCH','BREACH','BREATH','BRIDGE','BRIGHT','BROKEN','BRONZE','BUBBLE',
  'BUDGET','BUFFER','BUNDLE','BURDEN','BUREAU','BUTTON','CABLES','CAMERA',
  'CANCEL','CARBON','CAREER','CASTLE','CASUAL','CAUGHT','CAUSED','CENTER',
  'CENTRE','CHANCE','CHANGE','CHARGE','CHOSEN','CHURCH','CIRCLE','CINEMA',
  'CLAIMS','CLAUSE','CLEVER','CLIENT','CLOSER','COBALT','CODING','COFFEE',
  'COLONY','COLUMN','COMBAT','COMMIT','COMMON','COMPLY','COPPER','CORNER',
  'COSMIC','COTTON','COUPLE','COURSE','COUSIN','CREATE','CREDIT','CRISIS',
  'CUSTOM','DAMAGE','DANGER','DEBATE','DECADE','DECIDE','DECREE','DEFEAT',
  'DEFEND','DEFINE','DEGREE','DEMAND','DEPLOY','DEPICT','DERIVE','DESERT',
  'DESIGN','DESIRE','DETAIL','DETECT','DEVICE','DEVOTE','DIFFER','DILUTE',
  'DINNER','DIRECT','DOUBLE','DRYING','DURING','EASIER','EASILY','EATING',
  'EDITOR','EFFECT','EFFORT','EIGHTH','EMPLOY','ENABLE','ENDURE','ENERGY',
  'ENGAGE','ENGINE','ENOUGH','ENSURE','ENTIRE','ENTITY','EQUITY','ESCAPE',
  'ESTATE','ETHNIC','EVOLVE','EXCEED','EXCEPT','EXCITE','EXCUSE','EXEMPT',
  'EXPAND','EXPECT','EXPERT','EXPORT','EXPOSE','EXTEND','EXTENT','FABRIC',
  'FACTOR','FAIRLY','FALLEN','FAMILY','FAMINE','FAMOUS','FATHER','FAULTY',
  'FAVOUR','FELINE','FELLOW','FEMALE','FIERCE','FIGURE','FILTER','FINALE',
  'FINGER','FLIGHT','FLOWER','FLYING','FOLLOW','FORCED','FOREST','FORGET',
  'FORMAL','FORMAT','FORMER','FOSSIL','FOSTER','FOURTH','FREEZE','FRENCH',
  'FRIEND','FROZEN','FULFIL','FUNDED','FUTURE','GALAXY','GAMBLE','GARDEN',
  'GATHER','GENDER','GENTLE','GENTLY','GIFTED','GLOBAL','GOLDEN','GOVERN',
  'GRAVEL','GROWTH','GUILTY','GUITAR','HANDLE','HARDEN','HARDLY','HAZARD',
];

export function getWordList(length: number): string[] {
  switch (length) {
    case 4: return WORDS_4;
    case 5: return WORDS_5;
    case 6: return WORDS_6;
    default: return WORDS_5;
  }
}

export function getRandomWord(length: number): string {
  const words = getWordList(length);
  return words[Math.floor(Math.random() * words.length)];
}

export function isValidWord(word: string, length: number): boolean {
  const words = getWordList(length);
  return words.includes(word.toUpperCase());
}
